### ISSUE TITLE
No window

### ISSUE THREAD

**Issue by darkzbaron** [scheb/sound-to-light-osc#3]
Hi there, the application launches with no error but there is no window appearing. I am on Windows 10 and running your QT5 version. Thanks!

**Comment by scheb** [comment]
Well, check for errors. I haven't used it in a year or so. Could be that some dependency changed.

**Comment by darkzbaron** [comment]
Hi there, thanks for your quick reply. It looks like a windows issue as per https://stackoverflow.com/questions/43218064/pyqt5-5-8-2-doesnt-function-on-windows-10

I will try and revert
